language: python

sudo: false

python:
  - "2.7"

addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev

env:
  - TOX_ENV=py27
  - TOX_ENV=py34

install:
  - "pip install tox"
  - "pip install -r test-requirements.txt"
  - "pip install coveralls"

script: tox -e $TOX_ENV

after_success: coveralls
