language: python

sudo: false

python:
  - "2.7"
  - "3.5"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip atlas numpy scipy libnetcdf netcdf4 pandas matplotlib pytest
  - pip install -r test-requirements.txt
  - python -c "import oceansdb; oceansdb.utils.dbsource('WOA13', 'TEMP')"
  - python -c "import oceansdb; oceansdb.utils.dbsource('ETOPO', 'DEPTH')"
  - pip install codecov pytest-cov
  - python setup.py install

script:
  - py.test --cov --cov-report=term-missing -vv

after_success:
  - codecov
